import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "../components/HomeComponents/Footer.jsx";
import Navbar from "../components/HomeComponents/Navbar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="mb-10  space-y-20 ">{children}</div>
        <div className="mt-20 px-2">
          <Footer />
        </div>
      </body>
    </html>
  );
}
