import Navbar from '../components/HomeComponents/Navbar.jsx'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/HomeComponents/Footer.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body className={inter.className}>
   
   <Navbar/>
   <div className="mb-10  space-y-20 bg-sky-50"> 
             {children}
           </div>
   
   <div className="mt-20 px-2"> 
   <Footer/>
           </div>
         
   
         </body>
    </html>
  )
}
